### ISSUE TITLE
Target Cascade

### ISSUE THREAD

**Issue by cyberphantom** [CoordinatedControl/ArDroneVisualNavigation#1]
Hi,
I'm trying to do the same as you are doing here, i'm working on better way to track an object.
I didn't ran your code yet but please can you tell me what is the xml file descriptor image that you are detecting?
I want to dynamically create this cascade in real time. 

Thank You,

**Comment by nikv96** [comment]
Hello, thanks for your interest in this project. The cascade file is a descriptor for a known target (a circle with a cross inside). I used the OpenCV traincascade function (haar training) to create this model. A reference tutorial can be found [here](https://pythonprogramming.net/haar-cascade-object-detection-python-opencv-tutorial/). You can't run it in real time. However, you may consider exploring other options such as trackers (http://docs.opencv.org/3.0-beta/modules/tracking/doc/tracker_algorithms.html).

**Comment by cyberphantom** [comment]
thank you so much for your valuable info.
I created a canvas that has png streaming inside it and I want to assign any object within the stream so i got the bounding box and it will be a target, then I plan to create the haar cascade to be able to get detected but you saying this can't be done in real time. what about TLD method if you heard about it, the author detect any object in real time, so it should be a way to do that with ardrone

**Comment by nikv96** [comment]
I've seen best results for such a tracker in this [paper](http://www.cs.colostate.edu/~draper/papers/bolme_cvpr10.pdf). An OpenCV 3 implementation can be found in the samples - https://github.com/opencv/opencv/blob/master/samples/python/mosse.py.

**Comment by cyberphantom** [comment]
Great! 
I'll first try to implement the haar cascade target creation and then try to see the fastest tracker. 
One more thing, I guess node-opencv doesn't have support for openCV3 yet upon my knowledge. I'm using nodejs. I used to implement in ROS and C++ but nodejs is much easier to debug.
Your code will help a lot in the future. Placing an image sample of your target will be helpful.
